name: "Moon Estate - Plan"
on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init (Backendless)
        run: tofu init -backend=false
      - name: OpenTofu Validate
        run: tofu validate
  
  plan:
    needs: validate
    environment: personal
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_bedrock_vault_s3: ${{ secrets.TF_VAR_BEDROCK_VAULT_S3 }}
      TF_VAR_estate_maintainer_arn: ${{ secrets.TF_VAR_ESTATE_MAINTAINER_ARN }}
      TF_VAR_github_oidc_role_arn: ${{ secrets.TF_VAR_GITHUB_OIDC_ROLE_ARN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-session-name: "tsukiyou-session-plan"

      - name: TF_VAR Guard
        run: |
          echo "Verifying all TF_VARs are populated..."
          # Scan environment for TF_VARs with empty values
          EMPTY_VARS=$(env | grep '^TF_VAR_' | awk -F= '$2=="" {print $1}')
          
          if [ ! -z "$EMPTY_VARS" ]; then
            echo "ERROR: The following variables are empty in the environment:"
            echo "$EMPTY_VARS"
            echo "Please check your GitHub Secrets and Variables."
            exit 1
          fi
          echo "All TF_VARs validated."

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        run: |
          tofu init \
            -backend-config="bucket=${{ secrets.S3_BACKEND_NAME }}" \
            -backend-config="key=foundation/terraform.tfstate" \
            -backend-config="encrypt=true"

      - name: OpenTofu Plan
        run: tofu plan -no-color
